name: Linter (Hadolint)

on:
    push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint files
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true